#!/bin/sh
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

by_name=""
by_time="date"
by_size="size"
by_se="seeds"
by_le="leechs"

SORT="$by_name"
PAGE=1
SEARCH=""
DOMAIN="https://www.limetorrents.pro"
DELIM="\t"

C_LE="31"
C_SE="32"
C_SIZE="33"
C_HEALTH="35"
C_TIME="36"
C_NAME="39"
COLOR=1

alias ucurl='curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36" -H "Accept-Encoding: gzip, deflate" --compressed'

while [ $# -gt 0 ]
do
  case "$1" in
    -s|--sort)
      case "$2" in
        name) SORT=$by_name;;
        size) SORT=$by_size;;
        time) SORT=$by_time;;
        se) SORT=$by_se;;
        le) SORT=$by_le;;
      esac
      shift 2;;
    -h|--help)
        NAME="$(basename "$0")"
        printf "%s [OPTION]... [PATTERN]\nSearch for PATTERN in lt.\nExample: %s -s size -p 2 'archlinux'\n\n" "$NAME" "$NAME"
        printf "Options:\n  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, time, se, le\n"
        printf "  -d,  --domain DOMAIN\t\tset domain to DOMAIN\n"
        printf "  -D,  --delimiter DELIM\tset delimiter to DELIM\n"
        printf "  -p,  --page NUM\t\tshow page at NUM\n"
        printf "  -c,  --color\t\t\tcolor output\n"
        printf "  -C,  --no-color\t\tdisable coloring of output\n"
        printf "  -h,  --help\t\t\tshow help\n"
        printf "\nMagnet link will be copied via xclip.\n"
        exit 0;;
    -c|--color)
        COLOR=1
        shift;;
    -C|--no-color)
        COLOR=0
        shift;;
    -d|--domain)
        DOMAIN="$2"
        shift 2;;
    -p|--page)
        PAGE="$2"
        shift 2;;
    -D|--delimiter)
        DELIM="$2"
        shift 2;;
    *)
      SEARCH="$1"
      shift;;
  esac
done

SEARCHP=$(echo "$SEARCH" | tr ' .+/_:;' '-')

t1=$(mktemp)
t2=$(mktemp)
t_time=$(mktemp)
t_size=$(mktemp)
t_se=$(mktemp)
t_le=$(mktemp)
t_health=$(mktemp)
t_name=$(mktemp)
t_link=$(mktemp)
trap 'rm "$t1" "$t2" "$t_time" "$t_size" "$t_se" "$t_le" "$t_health" "$t_name" "$t_link"' EXIT

ucurl -g -L -s "$DOMAIN/search/all/$SEARCHP/$SORT/$PAGE/" | hgrep 'table +class="table2"; td' > "$t1"
hgrep 'td +class="tdnormal" @p"%i\n"' "$t1" > "$t2"
grep -v ' - ' "$t2" > "$t_size"
sed '/ - /!d; s/ - .*//' "$t2" > "$t_time"
hgrep 'td +class="tdseed" @p"%i\n"' "$t1" > "$t_se"
hgrep 'td +class="tdleech" @p"%i\n"' "$t1" > "$t_le"
hgrep 'td +class="tdright"; div @p"%(class)a\n"' "$t1" > "$t_health"
hgrep 'td +class="tdleft"; a +href=".*\.html" @p"%i\n"' "$t1" > "$t_name"
hgrep 'td +class="tdleft"; a +href=".*\.html" @p"'$DOMAIN'/%(href)a\n"' "$t1" > "$t_link"


color_lines() {
    sed "s/^/\x1b[$1m/; s/$/\x1b[0m/" "$2" > "$3"
    cp "$3" "$2"
}

if [ "$COLOR" -eq 1 ]
then
    color_lines "$C_SIZE" "$t_size" "$t1"
    color_lines "$C_NAME" "$t_name" "$t1"
    color_lines "$C_LE" "$t_le" "$t1"
    color_lines "$C_SE" "$t_se" "$t1"
    color_lines "$C_TIME" "$t_time" "$t1"
    color_lines "$C_HEALTH" "$t_health" "$t1"
fi

paste -d "$DELIM" "$t_name" "$t_time" "$t_size" "$t_se" "$t_le" "$t_health" | nl
printf 'num> '
read -r NUMBER
[ "$NUMBER" -gt 0 ] && ucurl -L -g -s "$(sed "s/ /%20/g; ${NUMBER}q;d" "$t_link")" | grep -oE -m 1 'magnet:\?[^"]+' | tee /dev/stderr | tr -d '\n' | xclip -sel clip
